"""Adicionando user na tabela todo

Revision ID: c4c4d618ce35
Revises: 7e653c1bbf60
Create Date: 2025-10-08 22:17:59.972114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4c4d618ce35'
down_revision: Union[str, Sequence[str], None] = '7e653c1bbf60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
